EventForm: added warning slot no-data
jabardigitalservice/pikobar-rapidtest-backoffice pull request #28
Opened 2020-10-01 10:51 UTC by maruf12

2020-10-02 07:15 UTC, yohang88 requested changes
minor aja @maruf12

2020-10-02 07:15 UTC, yohang88 commented on components/global/PkbrCombobox.vue
> +              Data "<strong>{{ search }}</strong
ini kenapa tag `</strong>`kepotong ya? begitu juga yang di bawah.

2020-10-02 07:27 UTC, maruf12 commented on components/global/PkbrCombobox.vue
> +              Data "<strong>{{ search }}</strong
@yohang88 ini linternya mas waktu disave dia jadi kebawah

2020-10-02 07:59 UTC, yohang88 commented on components/global/PkbrCombobox.vue
> +              Data "<strong>{{ search }}</strong
@maruf12 berarti harus diperbaiki manual 😁

2020-10-05 05:15 UTC, maruf12 commented on components/global/PkbrCombobox.vue
> +              Data "<strong>{{ search }}</strong
@yohang88 Setelah saya telusuri ini karena rules dari prettiernya. bahkan rules prettier ini yang bikin dulu kang nuris mau running jadi banyak yang error. Tadinya mau saya perbaiki prettiernya tapi itu malah merubah semua style code yang udah ada dan itu cukup riskan sih. Jadinya saya perbaiki manual sesuai saran mas yoga aja.

2020-10-05 06:18 UTC, yohang88 approved these changes

2020-10-05 06:18 UTC, merged