hide button integrasi data labkes
jabardigitalservice/pikobar-rapidtest-backoffice pull request #65
Opened 2020-12-16 09:18 UTC by maruf12

Preview:
Menyembunyikan tombol integrasi data labkes

2020-12-16 09:24 UTC, yohang88 approved these changes

2020-12-16 09:25 UTC, yohang88 requested changes
Dibuat config aja @maruf12, dan configurasi bisa diubah-ubah pakai env variables. Sehingga tidak perlu hardcode untuk menyalakan/mematikan fungsional.

2020-12-16 09:45 UTC, maruf12 commented
> Dibuat config aja @maruf12, dan configurasi bisa diubah-ubah pakai env variables. Sehingga tidak perlu hardcode untuk menyalakan/mematikan fungsional.

@yohang88 konfigurasi yang dimaksud ini harus pake remote config kah atau bisa cukup pake env varible aja mas?

2020-12-16 16:53 UTC, yohang88 commented
> > Dibuat config aja @maruf12, dan configurasi bisa diubah-ubah pakai env variables. Sehingga tidak perlu hardcode untuk menyalakan/mematikan fungsional.
> 
> @yohang88 konfigurasi yang dimaksud ini harus pake remote config kah atau bisa cukup pake env varible aja mas?

Cukup pakai env variable aja @maruf12

2020-12-17 03:32 UTC, yohang88 approved these changes

2020-12-17 03:32 UTC, merged